# ─────────────────────────────────────────
#  THEME: forest dark
#  old growth canopy, moss & rain, silence
# ─────────────────────────────────────────

font-family = Hack Nerd Font
font-size = 14
font-feature = +calt
font-feature = +liga
font-thicken = false

cursor-style = underline
cursor-style-blink = true
cursor-color = #7eff47
cursor-opacity = 1.0

background = #050e06
foreground = #c8e8c0

palette = 0=#0d1f0e
palette = 8=#1a3b1c
palette = 1=#e05a5a
palette = 9=#ff7070
palette = 2=#4caf50
palette = 10=#69c76d
palette = 3=#c8b400
palette = 11=#e0cc00
palette = 4=#4488aa
palette = 12=#5599bb
palette = 5=#8b6b4a
palette = 13=#aa8866
palette = 6=#26a69a
palette = 14=#33c0b8
palette = 7=#b8d8b0
palette = 15=#d8f0d0

selection-background = #1a3b1c
selection-foreground = #d8f0d0

background-opacity = 0.91
background-blur = 20

window-padding-x = 18
window-padding-y = 13
window-padding-balance = true
window-padding-color = extend
window-decoration = auto
window-theme = dark
window-colorspace = display-p3

mouse-hide-while-typing = true
minimum-contrast = 1.2
scrollback-limit = 10000000
unfocused-split-opacity = 0.68
alpha-blending = linear-corrected
